# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port

# For a complete list of properties you can include: 
#   http://wiki.developers.facebook.com/index.php/ApplicationProperties

development:
  api_key: 7c5d9d041a99c03159bbaf537ac42791
  secret_key: ac968876a0fa4eb1013fe120a30f218e
  xd_receiver: /xd_receiver.html
  pretty_errors: false
  set_asset_host_to_callback_url: true

  application_name: "Schacht"
  canvas_name: schacht
  callback_url: http://web1.tunnlr.com:10107/
  authorize_url: http://web1.tunnlr.com:10107/callback/install
  uninstall_url: http://web1.tunnlr.com:10107/callback/remove
  connect_url: http://web1.tunnlr.com:10107
    
  tunnel:
    public_host_username: tunnlr11
    public_host: ssh1.tunnlr.com
    public_port: 10107
    local_port: 3000
    
keith_development:
  api_key: 7c5d9d041a99c03159bbaf537ac42791
  secret_key: ac968876a0fa4eb1013fe120a30f218e
  xd_receiver: /xd_receiver.html
  pretty_errors: false
  set_asset_host_to_callback_url: true

  application_name: "Schacht"
  canvas_name: schacht
  callback_url: http://web1.tunnlr.com:10107/
  authorize_url: http://web1.tunnlr.com:10107/callback/install
  uninstall_url: http://web1.tunnlr.com:10107/callback/remove
  connect_url: http://web1.tunnlr.com:10107
    
  tunnel:
    public_host_username: tunnlr11
    public_host: ssh1.tunnlr.com
    public_port: 10107
    local_port: 3000
  
test:
  api_key: a7dd67a42b0ea8180a511ccf82d6fee3
  secret_key: 275704ec8576de1a475952999ea9b293
  canvas_name: rml-gardens-test
  callback_url: 
  pretty_errors: false
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: reuven
    public_host: lerner.co.il
    public_port: 3456
    local_port: 3457

production:
  api_key: 2320ce2a18e17dff0610418bec440eb4
  secret_key: 7f32f29a9518c7cf1ea79a14ef2bdeba
  xd_receiver: /xd_receiver.html
  pretty_errors: false
  set_asset_host_to_callback_url: true

  application_name: "My Bimbo"
  canvas_name: mybimbo
  callback_url: http://life-rpg.heroku.com/
  authorize_url: http://life-rpg.heroku.com/callback/install
  uninstall_url: http://life-rpg.heroku.com/callback/remove
  connect_url: http://life-rpg.heroku.com
