# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port

development:
  api_key: 6535b158e7c39c800864794452ffa351
  secret_key: dc22178f336969105809b40ab8beb772
  canvas_page_name:  schacht-tictactoe
  callback_url: http://web1.tunnlr.com:10107
  pretty_errors: false
  set_asset_host_to_callback_url: true
  tunnel:
                 public_host_username: tunnlr11
                 public_host: ssh1.tunnlr.com
                 public_port: 10107
                 local_port: 3000

test:
  api_key: a7dd67a42b0ea8180a511ccf82d6fee3
  secret_key: 275704ec8576de1a475952999ea9b293
  canvas_page_name: rml-gardens-test
  callback_url: http://lerner.co.il:3456/
  pretty_errors: false
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: reuven
    public_host: lerner.co.il
    public_port: 3456
    local_port: 3457

production:
  api_key: API_KEY_FOR_YOUR_HEROKU_FACEBOOK_APP
  secret_key: SECRET_FOR_YOUR_HEROKU_FACEBOOK_APP
  canvas_page_name: http://apps.facebook.com/HEROKU_DOMAIN_NAME/
  callback_url: http://HEROKU_DOMAIN_NAME.heroku.com/
  pretty_errors: true
