keith_development:
  api_key: 6535b158e7c39c800864794452ffa351
  secret: dc22178f336969105809b40ab8beb772
  api_id: 311644815918
  canvas: schacht-armymen
  properties:
    callback_url: http://web1.tunnlr.com:10107/
    application_name: "schacht-armymen"
    use_iframe: 1

david_development:
  api_key: 018e5918042c312e26b24f65cdd1eaf1
  secret: 7c1bf5e64b745e591c688d1a260f9285
  api_id: 301495457912
  canvas: mbfdavid
  properties:
    callback_url: http://ec2-184-73-26-17.compute-1.amazonaws.com/
    application_name: "Army Men (david)"
    use_iframe: 1

production:
  api_key: 871a7b5c8e35f5b377e40baca570a2e8
  secret: 311d5bbb39b08560ec17935381cb204c
  api_id: 323626737046
  canvas: armymen_en
  properties:
    callback_url: http://furious-planet-66.heroku.com/
    application_name: "Army Men"
    use_iframe: 1
